# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Tiktok\fSeeding.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fSeeding(object):
    def setupUi(self, fSeeding):
        fSeeding.setObjectName("fSeeding")
        fSeeding.resize(703, 861)
        fSeeding.setStyleSheet("/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"\n"
"SET APP STYLESHEET - FULL STYLES HERE\n"
"DARK THEME - DRACULA COLOR BASED\n"
"\n"
"///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"\n"
"\n"
"QGroupBox{\n"
"\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(255, 255, 255);}\n"
"QWidget{\n"
"    background-color: rgb(40, 44, 52);\n"
"    color: rgb(221, 221, 221);\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(33, 37, 43, 180);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(255, 121, 198);\n"
"    text-align: left;\n"
"    padding-left: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border: none;\n"
"    gridline-color: rgb(44, 49, 58);\n"
"\n"
"}\n"
"QTableWidget {    \n"
"    background-color: transparent;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 58);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: rgb(33, 37, 43);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QHeaderView {\n"
"    qproperty-defaultAlignment: AlignHCenter AlignVCenter;\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(33, 37, 43);\n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"LineEdit */\n"
"QLineEdit {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QPlainTextEdit  QScrollBar:vertical {\n"
"    width: 8px;\n"
" }\n"
"QPlainTextEdit  QScrollBar:horizontal {\n"
"    height: 8px;\n"
" }\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(189, 147, 249);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(189, 147, 249);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CheckBox */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(255, 121, 198);    \n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 5px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CommandLinkButton */\n"
"QCommandLinkButton {    \n"
"    color: rgb(255, 121, 198);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 170, 255);\n"
"}\n"
"QCommandLinkButton:hover {    \n"
"    color: rgb(255, 170, 255);\n"
"    background-color: rgb(44, 49, 60);\n"
"}\n"
"QCommandLinkButton:pressed {    \n"
"    color: rgb(189, 147, 249);\n"
"    background-color: rgb(52, 58, 71);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Button */\n"
"QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
" QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
" QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(fSeeding)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBoxLinkVideo = QtWidgets.QGroupBox(fSeeding)
        self.groupBoxLinkVideo.setCheckable(True)
        self.groupBoxLinkVideo.setChecked(False)
        self.groupBoxLinkVideo.setObjectName("groupBoxLinkVideo")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxLinkVideo)
        self.gridLayout.setContentsMargins(-1, 15, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_5 = QtWidgets.QFrame(self.groupBoxLinkVideo)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBoxDelay = QtWidgets.QSpinBox(self.frame_5)
        self.spinBoxDelay.setProperty("value", 5)
        self.spinBoxDelay.setObjectName("spinBoxDelay")
        self.horizontalLayout_3.addWidget(self.spinBoxDelay)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.spinBoxDelay_2 = QtWidgets.QSpinBox(self.frame_5)
        self.spinBoxDelay_2.setProperty("value", 10)
        self.spinBoxDelay_2.setObjectName("spinBoxDelay_2")
        self.horizontalLayout_3.addWidget(self.spinBoxDelay_2)
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.gridLayout.addWidget(self.frame_5, 4, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.groupBoxLinkVideo)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.textComment = QtWidgets.QPlainTextEdit(self.frame_3)
        self.textComment.setObjectName("textComment")
        self.verticalLayout_3.addWidget(self.textComment)
        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.groupBoxLinkVideo)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.textLinkVideo = QtWidgets.QPlainTextEdit(self.frame)
        self.textLinkVideo.setObjectName("textLinkVideo")
        self.horizontalLayout.addWidget(self.textLinkVideo)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.groupBoxLinkVideo)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cbView = QtWidgets.QCheckBox(self.frame_13)
        self.cbView.setObjectName("cbView")
        self.gridLayout_3.addWidget(self.cbView, 1, 0, 1, 1)
        self.cbComment = QtWidgets.QCheckBox(self.frame_13)
        self.cbComment.setObjectName("cbComment")
        self.gridLayout_3.addWidget(self.cbComment, 0, 0, 1, 1)
        self.cbLike = QtWidgets.QCheckBox(self.frame_13)
        self.cbLike.setObjectName("cbLike")
        self.gridLayout_3.addWidget(self.cbLike, 2, 0, 1, 1)
        self.cbSave = QtWidgets.QCheckBox(self.frame_13)
        self.cbSave.setObjectName("cbSave")
        self.gridLayout_3.addWidget(self.cbSave, 0, 1, 1, 1)
        self.cbCopy = QtWidgets.QCheckBox(self.frame_13)
        self.cbCopy.setObjectName("cbCopy")
        self.gridLayout_3.addWidget(self.cbCopy, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_13, 1, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.groupBoxLinkVideo)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.frame_9)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.spinBoxTimeView = QtWidgets.QSpinBox(self.frame_9)
        self.spinBoxTimeView.setMaximum(9999)
        self.spinBoxTimeView.setProperty("value", 5)
        self.spinBoxTimeView.setObjectName("spinBoxTimeView")
        self.horizontalLayout_7.addWidget(self.spinBoxTimeView)
        self.label_14 = QtWidgets.QLabel(self.frame_9)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.spinBoxTimeView_2 = QtWidgets.QSpinBox(self.frame_9)
        self.spinBoxTimeView_2.setMaximum(9999)
        self.spinBoxTimeView_2.setProperty("value", 10)
        self.spinBoxTimeView_2.setObjectName("spinBoxTimeView_2")
        self.horizontalLayout_7.addWidget(self.spinBoxTimeView_2)
        self.label_29 = QtWidgets.QLabel(self.frame_9)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_7.addWidget(self.label_29)
        self.gridLayout.addWidget(self.frame_9, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxLinkVideo, 0, 0, 1, 1)
        self.groupBoxFollow = QtWidgets.QGroupBox(fSeeding)
        self.groupBoxFollow.setCheckable(True)
        self.groupBoxFollow.setChecked(False)
        self.groupBoxFollow.setObjectName("groupBoxFollow")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxFollow)
        self.verticalLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.groupBoxFollow)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        self.textLinkUser = QtWidgets.QPlainTextEdit(self.frame_2)
        self.textLinkUser.setObjectName("textLinkUser")
        self.horizontalLayout_2.addWidget(self.textLinkUser)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_7 = QtWidgets.QFrame(self.groupBoxFollow)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.spinBoxDelayFollow = QtWidgets.QSpinBox(self.frame_7)
        self.spinBoxDelayFollow.setProperty("value", 5)
        self.spinBoxDelayFollow.setObjectName("spinBoxDelayFollow")
        self.horizontalLayout_4.addWidget(self.spinBoxDelayFollow)
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.spinBoxDelayFollow_2 = QtWidgets.QSpinBox(self.frame_7)
        self.spinBoxDelayFollow_2.setProperty("value", 10)
        self.spinBoxDelayFollow_2.setObjectName("spinBoxDelayFollow_2")
        self.horizontalLayout_4.addWidget(self.spinBoxDelayFollow_2)
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout_2.addWidget(self.frame_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.groupBoxFollow, 0, 1, 1, 1)
        self.groupBoxStory = QtWidgets.QGroupBox(fSeeding)
        self.groupBoxStory.setCheckable(True)
        self.groupBoxStory.setChecked(False)
        self.groupBoxStory.setObjectName("groupBoxStory")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxStory)
        self.verticalLayout.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_8 = QtWidgets.QFrame(self.groupBoxStory)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.spinBoxTimeStory = QtWidgets.QSpinBox(self.frame_8)
        self.spinBoxTimeStory.setMaximum(9999)
        self.spinBoxTimeStory.setProperty("value", 5)
        self.spinBoxTimeStory.setObjectName("spinBoxTimeStory")
        self.horizontalLayout_6.addWidget(self.spinBoxTimeStory)
        self.label_13 = QtWidgets.QLabel(self.frame_8)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.spinBoxTimeStory_2 = QtWidgets.QSpinBox(self.frame_8)
        self.spinBoxTimeStory_2.setMaximum(9999)
        self.spinBoxTimeStory_2.setProperty("value", 10)
        self.spinBoxTimeStory_2.setObjectName("spinBoxTimeStory_2")
        self.horizontalLayout_6.addWidget(self.spinBoxTimeStory_2)
        self.label_28 = QtWidgets.QLabel(self.frame_8)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_6.addWidget(self.label_28)
        self.verticalLayout.addWidget(self.frame_8)
        self.cbSaveVideo = QtWidgets.QCheckBox(self.groupBoxStory)
        self.cbSaveVideo.setObjectName("cbSaveVideo")
        self.verticalLayout.addWidget(self.cbSaveVideo)
        self.cbLikeStory = QtWidgets.QCheckBox(self.groupBoxStory)
        self.cbLikeStory.setObjectName("cbLikeStory")
        self.verticalLayout.addWidget(self.cbLikeStory)
        self.gridLayout_2.addWidget(self.groupBoxStory, 1, 0, 1, 1)
        self.groupBoxViewLive = QtWidgets.QGroupBox(fSeeding)
        self.groupBoxViewLive.setCheckable(True)
        self.groupBoxViewLive.setChecked(False)
        self.groupBoxViewLive.setObjectName("groupBoxViewLive")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBoxViewLive)
        self.verticalLayout_5.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_6 = QtWidgets.QFrame(self.groupBoxViewLive)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_24 = QtWidgets.QLabel(self.frame_6)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24)
        self.textLinkLive = QtWidgets.QLineEdit(self.frame_6)
        self.textLinkLive.setObjectName("textLinkLive")
        self.horizontalLayout_11.addWidget(self.textLinkLive)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.frame_14 = QtWidgets.QFrame(self.groupBoxViewLive)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.cbShareLive = QtWidgets.QCheckBox(self.frame_14)
        self.cbShareLive.setObjectName("cbShareLive")
        self.horizontalLayout_13.addWidget(self.cbShareLive)
        self.cbCommentLive = QtWidgets.QCheckBox(self.frame_14)
        self.cbCommentLive.setObjectName("cbCommentLive")
        self.horizontalLayout_13.addWidget(self.cbCommentLive)
        self.verticalLayout_5.addWidget(self.frame_14, 0, QtCore.Qt.AlignLeft)
        self.frame_4 = QtWidgets.QFrame(self.groupBoxViewLive)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.textCommentLive = QtWidgets.QPlainTextEdit(self.frame_4)
        self.textCommentLive.setObjectName("textCommentLive")
        self.verticalLayout_4.addWidget(self.textCommentLive)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.frame_12 = QtWidgets.QFrame(self.groupBoxViewLive)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_25 = QtWidgets.QLabel(self.frame_12)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_12.addWidget(self.label_25)
        self.spinBoxDelayViewLive = QtWidgets.QSpinBox(self.frame_12)
        self.spinBoxDelayViewLive.setMaximum(9999)
        self.spinBoxDelayViewLive.setProperty("value", 5)
        self.spinBoxDelayViewLive.setObjectName("spinBoxDelayViewLive")
        self.horizontalLayout_12.addWidget(self.spinBoxDelayViewLive)
        self.label_26 = QtWidgets.QLabel(self.frame_12)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_12.addWidget(self.label_26)
        self.spinBoxDelayViewLive_2 = QtWidgets.QSpinBox(self.frame_12)
        self.spinBoxDelayViewLive_2.setMaximum(9999)
        self.spinBoxDelayViewLive_2.setProperty("value", 10)
        self.spinBoxDelayViewLive_2.setObjectName("spinBoxDelayViewLive_2")
        self.horizontalLayout_12.addWidget(self.spinBoxDelayViewLive_2)
        self.label_27 = QtWidgets.QLabel(self.frame_12)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_12.addWidget(self.label_27, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_5.addWidget(self.frame_12, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_2.addWidget(self.groupBoxViewLive, 2, 0, 1, 2)

        self.retranslateUi(fSeeding)
        self.cbComment.toggled['bool'].connect(self.frame_3.setVisible)
        self.cbView.toggled['bool'].connect(self.frame_9.setVisible)
        self.cbCommentLive.toggled['bool'].connect(self.frame_4.setVisible)
        QtCore.QMetaObject.connectSlotsByName(fSeeding)

    def retranslateUi(self, fSeeding):
        _translate = QtCore.QCoreApplication.translate
        fSeeding.setWindowTitle(_translate("fSeeding", "Tương tác tiktok"))
        self.groupBoxLinkVideo.setTitle(_translate("fSeeding", "Link Video"))
        self.label_4.setText(_translate("fSeeding", "Độ trễ từ:"))
        self.label_5.setText(_translate("fSeeding", "đến:"))
        self.label_6.setText(_translate("fSeeding", "giây"))
        self.label_3.setText(_translate("fSeeding", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Nội dung bình luận</span></p></body></html>"))
        self.label.setText(_translate("fSeeding", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Link video:</span></p></body></html>"))
        self.textLinkVideo.setPlaceholderText(_translate("fSeeding", "https://www.tiktok.com/@username/video/id"))
        self.cbView.setText(_translate("fSeeding", "Xem video"))
        self.cbComment.setText(_translate("fSeeding", "Bình luận"))
        self.cbLike.setText(_translate("fSeeding", "Thích video"))
        self.cbSave.setText(_translate("fSeeding", "Lưu video"))
        self.cbCopy.setText(_translate("fSeeding", "Sao chép liên kết"))
        self.label_12.setText(_translate("fSeeding", "Thời gian xem từ:"))
        self.label_14.setText(_translate("fSeeding", "đến:"))
        self.label_29.setText(_translate("fSeeding", "giây"))
        self.groupBoxFollow.setTitle(_translate("fSeeding", "Follow user"))
        self.label_2.setText(_translate("fSeeding", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Link user:</span></p></body></html>"))
        self.textLinkUser.setPlaceholderText(_translate("fSeeding", "https://www.tiktok.com/@username"))
        self.label_7.setText(_translate("fSeeding", "Độ trễ theo dõi từ:"))
        self.label_8.setText(_translate("fSeeding", "đến:"))
        self.label_9.setText(_translate("fSeeding", "giây"))
        self.groupBoxStory.setTitle(_translate("fSeeding", "Lướt bản tin"))
        self.label_11.setText(_translate("fSeeding", "Thời gian lướt từ:"))
        self.label_13.setText(_translate("fSeeding", "đến:"))
        self.label_28.setText(_translate("fSeeding", "phút"))
        self.cbSaveVideo.setText(_translate("fSeeding", "Lưu video khi lướt"))
        self.cbLikeStory.setText(_translate("fSeeding", "Like video khi lướt"))
        self.groupBoxViewLive.setTitle(_translate("fSeeding", "View Live stream"))
        self.label_24.setText(_translate("fSeeding", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Link live:</span></p></body></html>"))
        self.textLinkLive.setPlaceholderText(_translate("fSeeding", "https://www.tiktok.com/@username/live"))
        self.cbShareLive.setText(_translate("fSeeding", "Sao chép liên kết"))
        self.cbCommentLive.setText(_translate("fSeeding", "Bình luận"))
        self.label_10.setText(_translate("fSeeding", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Nội dung bình luận</span></p></body></html>"))
        self.label_25.setText(_translate("fSeeding", "Thời gian xem:"))
        self.label_26.setText(_translate("fSeeding", "đến:"))
        self.label_27.setText(_translate("fSeeding", "phút"))
