# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Tiktok\fUpdate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fUpdateInfo(object):
    def setupUi(self, fUpdateInfo):
        fUpdateInfo.setObjectName("fUpdateInfo")
        fUpdateInfo.resize(289, 296)
        fUpdateInfo.setStyleSheet("QWidget{\n"
"    background-color: rgb(40, 44, 52);\n"
"    color: rgb(221, 221, 221);\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
" QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
" QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"\n"
"QGroupBox{\n"
"\n"
"border-radius: 5px;\n"
"border: none;\n"
"}\n"
"QLineEdit {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(fUpdateInfo)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(fUpdateInfo)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.gbName = QtWidgets.QGroupBox(fUpdateInfo)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.gbName.setFont(font)
        self.gbName.setStyleSheet("")
        self.gbName.setCheckable(True)
        self.gbName.setChecked(False)
        self.gbName.setObjectName("gbName")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbName)
        self.gridLayout_2.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnFileName = QtWidgets.QPushButton(self.gbName)
        self.btnFileName.setMinimumSize(QtCore.QSize(65, 30))
        self.btnFileName.setObjectName("btnFileName")
        self.gridLayout_2.addWidget(self.btnFileName, 1, 2, 1, 1)
        self.locationName = QtWidgets.QLineEdit(self.gbName)
        self.locationName.setObjectName("locationName")
        self.gridLayout_2.addWidget(self.locationName, 1, 1, 1, 1)
        self.cbTiktokID = QtWidgets.QCheckBox(self.gbName)
        self.cbTiktokID.setObjectName("cbTiktokID")
        self.gridLayout_2.addWidget(self.cbTiktokID, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.gbName, 1, 0, 1, 1)
        self.gbAvatar = QtWidgets.QGroupBox(fUpdateInfo)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.gbAvatar.setFont(font)
        self.gbAvatar.setStyleSheet("")
        self.gbAvatar.setCheckable(True)
        self.gbAvatar.setChecked(False)
        self.gbAvatar.setObjectName("gbAvatar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.gbAvatar)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.locationAvatar = QtWidgets.QLineEdit(self.gbAvatar)
        self.locationAvatar.setObjectName("locationAvatar")
        self.horizontalLayout_4.addWidget(self.locationAvatar)
        self.btnFolderAvatar = QtWidgets.QPushButton(self.gbAvatar)
        self.btnFolderAvatar.setMinimumSize(QtCore.QSize(65, 30))
        self.btnFolderAvatar.setObjectName("btnFolderAvatar")
        self.horizontalLayout_4.addWidget(self.btnFolderAvatar)
        self.gridLayout.addWidget(self.gbAvatar, 0, 0, 1, 1)
        self.gbBio = QtWidgets.QGroupBox(fUpdateInfo)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.gbBio.setFont(font)
        self.gbBio.setStyleSheet("")
        self.gbBio.setCheckable(True)
        self.gbBio.setChecked(False)
        self.gbBio.setObjectName("gbBio")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbBio)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.locationBio = QtWidgets.QLineEdit(self.gbBio)
        self.locationBio.setObjectName("locationBio")
        self.horizontalLayout.addWidget(self.locationBio)
        self.btnFileBio = QtWidgets.QPushButton(self.gbBio)
        self.btnFileBio.setMinimumSize(QtCore.QSize(65, 30))
        self.btnFileBio.setObjectName("btnFileBio")
        self.horizontalLayout.addWidget(self.btnFileBio)
        self.gridLayout.addWidget(self.gbBio, 2, 0, 1, 1)

        self.retranslateUi(fUpdateInfo)
        QtCore.QMetaObject.connectSlotsByName(fUpdateInfo)

    def retranslateUi(self, fUpdateInfo):
        _translate = QtCore.QCoreApplication.translate
        fUpdateInfo.setWindowTitle(_translate("fUpdateInfo", "Cập nhật thông tin"))
        self.label.setText(_translate("fUpdateInfo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-style:italic;\">Tự động tạo ngẫu nhiên TikTokID bằng tên!</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-style:italic;\">Tự động ngẫu nhiên tên và bio trong file!</span></p></body></html>"))
        self.gbName.setTitle(_translate("fUpdateInfo", "Tên"))
        self.btnFileName.setText(_translate("fUpdateInfo", "File Name"))
        self.cbTiktokID.setText(_translate("fUpdateInfo", "TikTokID"))
        self.gbAvatar.setTitle(_translate("fUpdateInfo", "Avatar"))
        self.btnFolderAvatar.setText(_translate("fUpdateInfo", "Folder Avatar"))
        self.gbBio.setTitle(_translate("fUpdateInfo", "Bio"))
        self.btnFileBio.setText(_translate("fUpdateInfo", "File Bio"))
