# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Tiktok\fSettingUpload.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fUpload(object):
    def setupUi(self, fUpload):
        fUpload.setObjectName("fUpload")
        fUpload.resize(845, 425)
        fUpload.setStyleSheet("/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"\n"
"SET APP STYLESHEET - FULL STYLES HERE\n"
"DARK THEME - DRACULA COLOR BASED\n"
"\n"
"///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"\n"
"\n"
"QGroupBox{\n"
"\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(255, 255, 255);}\n"
"QWidget{\n"
"    background-color: rgb(40, 44, 52);\n"
"    color: rgb(221, 221, 221);\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(33, 37, 43, 180);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(255, 121, 198);\n"
"    text-align: left;\n"
"    padding-left: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border: none;\n"
"    gridline-color: rgb(44, 49, 58);\n"
"\n"
"}\n"
"QTableWidget {    \n"
"    background-color: transparent;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 58);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: rgb(33, 37, 43);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QHeaderView {\n"
"    qproperty-defaultAlignment: AlignHCenter AlignVCenter;\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(33, 37, 43);\n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"LineEdit */\n"
"QLineEdit {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QPlainTextEdit  QScrollBar:vertical {\n"
"    width: 8px;\n"
" }\n"
"QPlainTextEdit  QScrollBar:horizontal {\n"
"    height: 8px;\n"
" }\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(189, 147, 249);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(189, 147, 249);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CheckBox */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(255, 121, 198);    \n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 5px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CommandLinkButton */\n"
"QCommandLinkButton {    \n"
"    color: rgb(255, 121, 198);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 170, 255);\n"
"}\n"
"QCommandLinkButton:hover {    \n"
"    color: rgb(255, 170, 255);\n"
"    background-color: rgb(44, 49, 60);\n"
"}\n"
"QCommandLinkButton:pressed {    \n"
"    color: rgb(189, 147, 249);\n"
"    background-color: rgb(52, 58, 71);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Button */\n"
"QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
" QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
" QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"\n"
"")
        self.gridLayout_3 = QtWidgets.QGridLayout(fUpload)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(fUpload)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.btnOpenContent = QtWidgets.QPushButton(fUpload)
        self.btnOpenContent.setMinimumSize(QtCore.QSize(64, 30))
        self.btnOpenContent.setMaximumSize(QtCore.QSize(97, 16777215))
        self.btnOpenContent.setObjectName("btnOpenContent")
        self.gridLayout_3.addWidget(self.btnOpenContent, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(fUpload)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rbOnlyContent = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbOnlyContent.setObjectName("rbOnlyContent")
        self.gridLayout_2.addWidget(self.rbOnlyContent, 1, 0, 2, 2)
        self.textContent = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.textContent.setObjectName("textContent")
        self.gridLayout_2.addWidget(self.textContent, 4, 0, 1, 1)
        self.rbContentLine = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbContentLine.setChecked(True)
        self.rbContentLine.setObjectName("rbContentLine")
        self.gridLayout_2.addWidget(self.rbContentLine, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(fUpload)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.rbRandomVideo = QtWidgets.QRadioButton(self.groupBox)
        self.rbRandomVideo.setObjectName("rbRandomVideo")
        self.gridLayout.addWidget(self.rbRandomVideo, 1, 0, 1, 1)
        self.locationFolderVideo = QtWidgets.QLineEdit(self.groupBox)
        self.locationFolderVideo.setObjectName("locationFolderVideo")
        self.gridLayout.addWidget(self.locationFolderVideo, 1, 1, 1, 1)
        self.rbOnlyVideo = QtWidgets.QRadioButton(self.groupBox)
        self.rbOnlyVideo.setChecked(True)
        self.rbOnlyVideo.setObjectName("rbOnlyVideo")
        self.gridLayout.addWidget(self.rbOnlyVideo, 0, 0, 1, 1)
        self.locationVideo = QtWidgets.QLineEdit(self.groupBox)
        self.locationVideo.setObjectName("locationVideo")
        self.gridLayout.addWidget(self.locationVideo, 0, 1, 1, 1)
        self.btnOpenFileVideo = QtWidgets.QPushButton(self.groupBox)
        self.btnOpenFileVideo.setMinimumSize(QtCore.QSize(60, 30))
        self.btnOpenFileVideo.setObjectName("btnOpenFileVideo")
        self.gridLayout.addWidget(self.btnOpenFileVideo, 0, 2, 1, 1)
        self.btnOpenFolderVideo = QtWidgets.QPushButton(self.groupBox)
        self.btnOpenFolderVideo.setMinimumSize(QtCore.QSize(60, 30))
        self.btnOpenFolderVideo.setObjectName("btnOpenFolderVideo")
        self.gridLayout.addWidget(self.btnOpenFolderVideo, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(fUpload)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 0, 1, 1)
        self.groupBoxSchedule = QtWidgets.QGroupBox(fUpload)
        self.groupBoxSchedule.setCheckable(True)
        self.groupBoxSchedule.setChecked(False)
        self.groupBoxSchedule.setObjectName("groupBoxSchedule")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxSchedule)
        self.horizontalLayout.setContentsMargins(-1, 15, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBoxSchedule)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBoxDay = QtWidgets.QSpinBox(self.groupBoxSchedule)
        self.spinBoxDay.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBoxDay.setMaximum(31)
        self.spinBoxDay.setObjectName("spinBoxDay")
        self.horizontalLayout.addWidget(self.spinBoxDay)
        self.label_4 = QtWidgets.QLabel(self.groupBoxSchedule)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.spinBoxHours = QtWidgets.QSpinBox(self.groupBoxSchedule)
        self.spinBoxHours.setMaximum(23)
        self.spinBoxHours.setObjectName("spinBoxHours")
        self.horizontalLayout.addWidget(self.spinBoxHours)
        self.label_5 = QtWidgets.QLabel(self.groupBoxSchedule)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.spinBoxMinutes = QtWidgets.QSpinBox(self.groupBoxSchedule)
        self.spinBoxMinutes.setMaximum(55)
        self.spinBoxMinutes.setSingleStep(5)
        self.spinBoxMinutes.setObjectName("spinBoxMinutes")
        self.horizontalLayout.addWidget(self.spinBoxMinutes)
        self.gridLayout_3.addWidget(self.groupBoxSchedule, 3, 1, 1, 1)

        self.retranslateUi(fUpload)
        QtCore.QMetaObject.connectSlotsByName(fUpload)

    def retranslateUi(self, fUpload):
        _translate = QtCore.QCoreApplication.translate
        fUpload.setWindowTitle(_translate("fUpload", "Tải lên video"))
        self.label_2.setText(_translate("fUpload", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Nội dung content </span><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">*</span></p></body></html>"))
        self.btnOpenContent.setText(_translate("fUpload", "Chọn nội dung"))
        self.rbOnlyContent.setText(_translate("fUpload", "Only content"))
        self.rbContentLine.setText(_translate("fUpload", "Content by line"))
        self.groupBox.setTitle(_translate("fUpload", "Video"))
        self.rbRandomVideo.setText(_translate("fUpload", "Random video folder"))
        self.rbOnlyVideo.setText(_translate("fUpload", "Only video"))
        self.btnOpenFileVideo.setText(_translate("fUpload", "File"))
        self.btnOpenFolderVideo.setText(_translate("fUpload", "Folder"))
        self.label.setText(_translate("fUpload", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Một số yêu cầu khi đăng video </span><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">*</span></p><p><span style=\" font-style:italic;\">• Video phải MP4 hoặc WebM</span></p><p><span style=\" font-style:italic;\">• Độ phân giải 780 x 1080 trở lên</span></p><p><span style=\" font-style:italic;\">• Tối đa 30 phút</span></p><p><span style=\" font-style:italic;\">• Ít hơn 2GB</span></p></body></html>"))
        self.groupBoxSchedule.setTitle(_translate("fUpload", "Lên lịch"))
        self.label_3.setText(_translate("fUpload", "Ngày:"))
        self.label_4.setText(_translate("fUpload", "Giờ:"))
        self.label_5.setText(_translate("fUpload", "Phút:"))
